spring:
  application:
    name: generic-stock-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    password: mypass
    username: postgres
    hikari:
      schema: stock
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8082